/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rsyntaxtextarea.SyntaxScheme;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author Jhona
 */
public class Ide extends javax.swing.JFrame {
    
    String[] options_name = { "GenericXML", "FuncionScript" };
    String[] options_ext =  { "gxml", "fs" };

    /**
     * Creates new form Ide
     */
    public Ide() {
        initComponents();
        addTab(null, options_ext[0]);
    }
    
    public void createTab(){
        //debo de pedir el nombre del archivo y su extension
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre", 
                "Nombre Tab", JOptionPane.INFORMATION_MESSAGE);
        //agrega el tab
        if(!nombre.equals(""))
        {
            String extension = (String)JOptionPane.showInputDialog(null, 
                "Seleccione la extension", "Extension", JOptionPane.INFORMATION_MESSAGE, 
                null, options_name, options_name[0]);
            
            extension = (extension.equals(options_name[0]))?options_ext[0]:options_ext[1];
            
            addTab(nombre, extension); 
        }
        else { JOptionPane.showMessageDialog(null, "Debe ingresar el nombre", "Informe de error", JOptionPane.ERROR_MESSAGE);}
    }
    
    /**
     * Si nombre es null colocar un tab por defecto ejemplo
     * Archivo ( posicion tab )
     * @param nombre 
     */
    public void addTab(String nombre, String ext){
        //creando tokensabstractos de las sintaxis
        /*AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory) TokenMakerFactory.getDefaultInstance();
        atmf.putMapping("GXMLSyntax", "GXML.Analizador.GXMLSyntax");
        atmf.putMapping("FSSyntax", "FS.Analizador.FSSyntax");*/
        
        //Colocar area de texto
        RSyntaxTextArea rsta = new RSyntaxTextArea();
        
        //Definiendo la sintaxis
        /*if(ext.equals(options[0])){ rsta.setSyntaxEditingStyle("GXMLSyntax"); }
        else{ rsta.setSyntaxEditingStyle("FSSyntax"); }
        rsta.setCodeFoldingEnabled(true);*/
        
        //Colocar un scrollpane
        RTextScrollPane rtsp = new RTextScrollPane(rsta, true);
        rtsp.setFoldIndicatorEnabled(true);
        rtsp.setIconRowHeaderEnabled(true);
        /*
        if(ext.equals(options[0]) || ext.equals(options[1]))
        {
            SyntaxScheme scheme = rsta.getSyntaxScheme();
            scheme.getStyle(Token.RESERVED_WORD).foreground = Color.BLUE;
            scheme.getStyle(Token.FUNCTION).foreground = Color.BLUE;
            scheme.getStyle(Token.LITERAL_STRING_DOUBLE_QUOTE).foreground = Color.ORANGE;
            scheme.getStyle(Token.IDENTIFIER).foreground = Color.RED;
            scheme.getStyle(Token.DATA_TYPE).foreground = Color.BLUE;
            scheme.getStyle(Token.COMMENT_EOL).foreground = Color.GRAY;
            scheme.getStyle(Token.COMMENT_MULTILINE).foreground = Color.GRAY;
            scheme.getStyle(Token.SEPARATOR).foreground = Color.black;
        }
        */
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(rtsp, BorderLayout.CENTER);
        
        if(nombre != null){
            String nameTab = nombre + "." + ext;
            tabcontrol.addTab(nameTab, pan);
        }else{
            int noTab = tabcontrol.getTabCount()+1;
            String nameTab = "Archivo_" + noTab + "." + ext;
            tabcontrol.addTab(nameTab, pan);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabcontrol = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        btn_abrir = new javax.swing.JMenuItem();
        btn_guardar = new javax.swing.JMenuItem();
        btn_guardarcomo = new javax.swing.JMenuItem();
        menu_tab = new javax.swing.JMenu();
        btn_nuevotab = new javax.swing.JMenuItem();
        btn_cerrartab = new javax.swing.JMenuItem();
        menu_errorees = new javax.swing.JMenu();
        btn_reporterror = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Extreme Editor");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-reproducir-en-círculo-48.png"))); // NOI18N

        menu_archivo.setText("Archivo");

        btn_abrir.setText("Abrir");
        menu_archivo.add(btn_abrir);

        btn_guardar.setText("Guardar");
        menu_archivo.add(btn_guardar);

        btn_guardarcomo.setText("Guardar Como");
        menu_archivo.add(btn_guardarcomo);

        jMenuBar1.add(menu_archivo);

        menu_tab.setText("Pestaña");

        btn_nuevotab.setText("Nuevo Tab");
        btn_nuevotab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevotabActionPerformed(evt);
            }
        });
        menu_tab.add(btn_nuevotab);

        btn_cerrartab.setText("Cerrar Tab");
        menu_tab.add(btn_cerrartab);

        jMenuBar1.add(menu_tab);

        menu_errorees.setText("Errores");

        btn_reporterror.setText("Reporte Errores");
        menu_errorees.add(btn_reporterror);

        jMenuBar1.add(menu_errorees);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(tabcontrol))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(jButton1)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabcontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevotabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevotabActionPerformed
        // TODO add your handling code here:
        createTab();
    }//GEN-LAST:event_btn_nuevotabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_abrir;
    private javax.swing.JMenuItem btn_cerrartab;
    private javax.swing.JMenuItem btn_guardar;
    private javax.swing.JMenuItem btn_guardarcomo;
    private javax.swing.JMenuItem btn_nuevotab;
    private javax.swing.JMenuItem btn_reporterror;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_errorees;
    private javax.swing.JMenu menu_tab;
    private javax.swing.JTabbedPane tabcontrol;
    // End of variables declaration//GEN-END:variables
}
