
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.fs;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser_fs extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser_fs() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser_fs(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser_fs(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\072\005\001\002\000\004\002\006\001" +
    "\002\000\004\002\000\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser_fs$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser_fs$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser_fs$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**
     * Método al que se llama automáticamente ante algún error sintactico.
     **/ 
    public void syntax_error(Symbol s) {
        StringBuilder m = new StringBuilder("Error Sintactico");
        int yline = s.left, ycol = s.right;

        if(s.left >= 0) {
        	m.append(" en la Linea " + (s.left));
        	if(s.right >= 0) {
        		m.append(" Columna " + (s.right));
        	}
        	m.append(". No se esperaba este componente: " + s.value + ".");
        }
        System.out.println(m);
    }

    /**
     * Método al que se llama automáticamente ante algún error sintáctico 
     * en el que ya no es posible una recuperación de errores.
     **/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        syntax_error(s);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser_fs$actions {
  private final Parser_fs parser;

  /** Constructor */
  CUP$Parser_fs$actions(Parser_fs parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser_fs$do_action_part00000000(
    int                        CUP$Parser_fs$act_num,
    java_cup.runtime.lr_parser CUP$Parser_fs$parser,
    java.util.Stack            CUP$Parser_fs$stack,
    int                        CUP$Parser_fs$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser_fs$result;

      /* select the action based on the action number */
      switch (CUP$Parser_fs$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser_fs$stack.elementAt(CUP$Parser_fs$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser_fs$stack.elementAt(CUP$Parser_fs$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser_fs$stack.elementAt(CUP$Parser_fs$top-1)).value;
		RESULT = start_val;
              CUP$Parser_fs$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser_fs$stack.elementAt(CUP$Parser_fs$top-1)), ((java_cup.runtime.Symbol)CUP$Parser_fs$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser_fs$parser.done_parsing();
          return CUP$Parser_fs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= mas 
            {
              Object RESULT =null;

              CUP$Parser_fs$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$Parser_fs$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser_fs$stack.peek()), RESULT);
            }
          return CUP$Parser_fs$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser_fs$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser_fs$do_action(
    int                        CUP$Parser_fs$act_num,
    java_cup.runtime.lr_parser CUP$Parser_fs$parser,
    java.util.Stack            CUP$Parser_fs$stack,
    int                        CUP$Parser_fs$top)
    throws java.lang.Exception
    {
              return CUP$Parser_fs$do_action_part00000000(
                               CUP$Parser_fs$act_num,
                               CUP$Parser_fs$parser,
                               CUP$Parser_fs$stack,
                               CUP$Parser_fs$top);
    }
}

}
