
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.fs;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pr_todos = 24;
  public static final int pr_nulo = 2;
  public static final int pr_funcion = 13;
  public static final int menor = 64;
  public static final int cori = 48;
  public static final int pr_crearreproductor = 39;
  public static final int cord = 49;
  public static final int punto = 50;
  public static final int pr_creartexto = 32;
  public static final int asigesp = 76;
  public static final int llai = 46;
  public static final int porigual = 73;
  public static final int pr_alguno = 25;
  public static final int pr_importar = 6;
  public static final int llad = 47;
  public static final int pr_descendente = 14;
  public static final int div = 59;
  public static final int pr_alclic = 41;
  public static final int pr_sino = 12;
  public static final int pr_minimo = 19;
  public static final int divigual = 75;
  public static final int pr_caso = 9;
  public static final int mas = 56;
  public static final int cadena = 79;
  public static final int dospuntos = 52;
  public static final int menorigual = 66;
  public static final int pr_detener = 7;
  public static final int decimal = 78;
  public static final int pr_selecciona = 8;
  public static final int pr_obtenerporetiqueta = 27;
  public static final int pr_creararraydesdearchivo = 16;
  public static final int masigual = 72;
  public static final int pr_leergxml = 26;
  public static final int or = 70;
  public static final int pr_falso = 4;
  public static final int mayorigual = 65;
  public static final int pr_var = 5;
  public static final int id = 80;
  public static final int pr_invertir = 17;
  public static final int pr_creardesplegable = 36;
  public static final int inter = 55;
  public static final int menmen = 62;
  public static final int ptcoma = 53;
  public static final int pr_alcerrar = 43;
  public static final int and = 69;
  public static final int mayor = 63;
  public static final int pr_buscar = 21;
  public static final int pr_retornar = 10;
  public static final int men = 57;
  public static final int pr_alcargar = 42;
  public static final int pr_crearcontrolnumerico = 35;
  public static final int pr_crearventana = 30;
  public static final int EOF = 0;
  public static final int pr_ascendente = 15;
  public static final int pr_si = 11;
  public static final int pr_crearboton = 37;
  public static final int pr_map = 22;
  public static final int error = 1;
  public static final int diferente = 68;
  public static final int entero = 77;
  public static final int pr_crearcontenedor = 31;
  public static final int pr_crearareatexto = 34;
  public static final int pari = 44;
  public static final int igualigual = 67;
  public static final int pr_verdadero = 3;
  public static final int pr_obtenerpornombre = 29;
  public static final int pot = 60;
  public static final int pard = 45;
  public static final int por = 58;
  public static final int pr_reducir = 23;
  public static final int pr_crearimagen = 38;
  public static final int pr_crearcajatexto = 33;
  public static final int pr_crearvideo = 40;
  public static final int coma = 51;
  public static final int not = 71;
  public static final int igual = 54;
  public static final int pr_filtrar = 20;
  public static final int menigual = 74;
  public static final int masmas = 61;
  public static final int pr_obtenerporid = 28;
  public static final int pr_maximo = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pr_nulo",
  "pr_verdadero",
  "pr_falso",
  "pr_var",
  "pr_importar",
  "pr_detener",
  "pr_selecciona",
  "pr_caso",
  "pr_retornar",
  "pr_si",
  "pr_sino",
  "pr_funcion",
  "pr_descendente",
  "pr_ascendente",
  "pr_creararraydesdearchivo",
  "pr_invertir",
  "pr_maximo",
  "pr_minimo",
  "pr_filtrar",
  "pr_buscar",
  "pr_map",
  "pr_reducir",
  "pr_todos",
  "pr_alguno",
  "pr_leergxml",
  "pr_obtenerporetiqueta",
  "pr_obtenerporid",
  "pr_obtenerpornombre",
  "pr_crearventana",
  "pr_crearcontenedor",
  "pr_creartexto",
  "pr_crearcajatexto",
  "pr_crearareatexto",
  "pr_crearcontrolnumerico",
  "pr_creardesplegable",
  "pr_crearboton",
  "pr_crearimagen",
  "pr_crearreproductor",
  "pr_crearvideo",
  "pr_alclic",
  "pr_alcargar",
  "pr_alcerrar",
  "pari",
  "pard",
  "llai",
  "llad",
  "cori",
  "cord",
  "punto",
  "coma",
  "dospuntos",
  "ptcoma",
  "igual",
  "inter",
  "mas",
  "men",
  "por",
  "div",
  "pot",
  "masmas",
  "menmen",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "igualigual",
  "diferente",
  "and",
  "or",
  "not",
  "masigual",
  "porigual",
  "menigual",
  "divigual",
  "asigesp",
  "entero",
  "decimal",
  "cadena",
  "id"
  };
}

